sudo: required

language: python

python:
  - "3.6"
  #- "nightly"

os:
  - linux

addons:
  apt:
    packages:
      - "python3-pip" 


before_install:
  - sudo bash scripts/geckodriver/download.sh travis

install:
  - sudo pip3 install -r requirements.txt
  - sudo python3 setup.py install

before_script:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


script:
  - sudo python3 test/test.py

branches:
  only:
    - staging